// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJmGsRSr7RIGLGaSx9Yrn54GAKY157T0',
    appId: '1:64441797919:web:a5c31e8efeb1479d69342a',
    messagingSenderId: '64441797919',
    projectId: 'chat-app-85619',
    authDomain: 'chat-app-85619.firebaseapp.com',
    storageBucket: 'chat-app-85619.appspot.com',
    measurementId: 'G-GHSHBHFT69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ9r7_iXdgFS_k9buhOucCJFNAgMtK2Uc',
    appId: '1:64441797919:android:66b39b8fb5ee7f9969342a',
    messagingSenderId: '64441797919',
    projectId: 'chat-app-85619',
    storageBucket: 'chat-app-85619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfCUQcv1KlnTGhdBKdwZQJu7UDkfKIPJQ',
    appId: '1:64441797919:ios:84d4a5bdbe3c8cb869342a',
    messagingSenderId: '64441797919',
    projectId: 'chat-app-85619',
    storageBucket: 'chat-app-85619.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfCUQcv1KlnTGhdBKdwZQJu7UDkfKIPJQ',
    appId: '1:64441797919:ios:84d4a5bdbe3c8cb869342a',
    messagingSenderId: '64441797919',
    projectId: 'chat-app-85619',
    storageBucket: 'chat-app-85619.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGJmGsRSr7RIGLGaSx9Yrn54GAKY157T0',
    appId: '1:64441797919:web:3decdaf6b38e223569342a',
    messagingSenderId: '64441797919',
    projectId: 'chat-app-85619',
    authDomain: 'chat-app-85619.firebaseapp.com',
    storageBucket: 'chat-app-85619.appspot.com',
    measurementId: 'G-5CP8JEGREB',
  );
}
